### ISSUE TITLE
localize "STR_CAU_ColorPicker_Title" returns "" when German langues is selected

### ISSUE THREAD

**Issue by R3voA3** [ConnorAU/A3ColorPicker#1]
![image](https://user-images.githubusercontent.com/17484252/59145261-872c8700-89e1-11e9-9da4-6c02f0bf2413.png)

![image](https://user-images.githubusercontent.com/17484252/59145263-8d226800-89e1-11e9-9c15-18a1d08b72e2.png)

**Comment by ConnorAU** [comment]
Resolved https://github.com/ConnorAU/A3ColorPicker/pull/3
